DUT:
  mode: SOCKET
  address: 129.196.136.130
  port: '3490'
  gpib: '6'
DMM:
  mode: SOCKET
  address: 10.205.92.183
  port: '3490'
  gpib: '6'
f884xA:
  mode: SOCKET
  address: 10.205.92.183
  port: '3490'
  gpib: '8'
